### ISSUE TITLE
Add search bar to events list fragment

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-organizer-android#1092]
### Feature Request

**Feature Description**
The Event brite app has a search bar at the top to search for events. This can be implemented in Orga App as well.

**Would you like to work on the issue?**
Yes

**Comment by AB261** [comment]
Hey can I work on this? Or is it done already?

**Comment by Masquerade0097** [comment]
@AB261 Yes, you can work on it.

**Comment by ShridharGoel** [comment]
Will be done after migration of Events module to Room database.

**Comment by 991rajat** [comment]
@iamareebjamal Is this issue still open?
