### ISSUE TITLE
Double elevation in tabs and action bar

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-organizer-android#1173]
### Bug Report    

**Actual Behaviour**
Double elevation is present in tabs and action bar of the app which needs to be removed.

**Android version and Phone Model**
Android 6.0.1 and Redmi Note 3

**Would you like to work on the issue?**
Yes

**Comment by tavishjain** [comment]
Is this still open ?
Can I make a PR to resolve this ?

**Comment by ShridharGoel** [comment]
Missing screenshots to understand the issue.

**Comment by iamareebjamal** [comment]
See the attendee fragment
