### ISSUE TITLE
Integrate Stripe Payments in app

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-organizer-android#1327]
### Feature Request

**Feature Description**

Integrate Payments with stripe for creating orders.
   
**Would you like to work on the issue?**

This is open for all and is meant to be handled after GSoC.

**Comment by iamareebjamal** [comment]
Yes

**Comment by Yahhi** [comment]
Is there any active work on the issue? Can I take it?

**Comment by Masquerade0097** [comment]
@Yahhi Yes, you can work on it.

**Comment by tavishjain** [comment]
In what way do we have to integrate the payments into the application ?
I mean whether only Google Pay or credit card information process ?

**Comment by Masquerade0097** [comment]
Stripe payment. Refer https://open-event-api-dev.herokuapp.com/#stripe-authorization
