### ISSUE TITLE
Replace the current database with Room

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-organizer-android#1348]
### Chore

**Description**
We should start using Room database (AAC) in the project.

**Would you like to work on the issue?**
No

**Comment by vanshikaarora** [comment]
Hey I would like to work upon this issue. Could you tell me which database are you using currently?

**Comment by iamareebjamal** [comment]
DBFlow

**Comment by vanshikaarora** [comment]
I am familiar with Room but I am not familiar with DBRoom.
Can i work upon this issue?

**Comment by iamareebjamal** [comment]
Yes

**Comment by tavishjain** [comment]
Can I work on this issue ? @iamareebjamal @ShridharGoel @Masquerade0097

**Comment by tavishjain** [comment]
Can I work on this ? @iamareebjamal @ShridharGoel @Masquerade0097

**Comment by ShridharGoel** [comment]
@tavishjain Yeah, go ahead.
