### ISSUE TITLE
Tickets list is not updated after creating new ticket

### ISSUE THREAD

**Issue by tavishjain** [fossasia/open-event-organizer-android#1446]
**Describe the bug**
Whenever we create a new ticket, and return to the screen containing the list of the tickets, then we need to manually refresh the contents to see the newly added ticket. 

**To Reproduce**
Go to the Tickets section, create a new ticket and return to the tickets screen. The new ticket will nnot be present there. 

**Expected behavior**
The list should be updated. 

**Logs**
NA

**Screenshots**
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/31106411/51257102-e6efaa80-19cc-11e9-9509-49f0f6fa621c.gif)

**Smartphone Info:**
|Device|         Redmi Note 4
|Android Version|  Nougat 7.1.1

**Additional context**

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by Shhreyya** [comment]
I want to work on this.
