### ISSUE TITLE
Apply spotless plugin

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-organizer-android#1716]
Apply the spotless plugin to improve code quality and refactor code according to java code style guideline.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
Work on it after most of PRs will merge due to conflicts.

**Comment by iamareebjamal** [comment]
In Java, there is no standard formatter unlike ktlint. Google formatter conflicts with IntelliJ's default formatter, which will lead to a lot of conflicts. So, will take up later

**Comment by naman653** [comment]
I would like to work on this issue.

**Comment by liveHarshit** [comment]
@iamareebjamal Now we should go for it?

**Comment by iamareebjamal** [comment]
Try it out

**Comment by adityastic** [comment]
@iamareebjamal should I try it out?

**Comment by iamareebjamal** [comment]
Sure
