### ISSUE TITLE
Write unit tests for AttendeesViewModel

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-organizer-android#1734]
**Describe the chore**
Write unit tests for AttendeesViewModel

**Would you like to work on the issue?**
Open to all.

**Comment by dipu989** [comment]
@ShridharGoel  I would like to work on this! 
Do I need to write tests on AttendeeCheckInView Model?

**Comment by ShridharGoel** [comment]
@dipu989 Go ahead. You have to write unit tests for `AttendeesViewModel`.

**Comment by dipu989** [comment]
@ShridharGoel  I can't find any file named AttendeesViewModel. There is one interface AttendeesView and one model AttendeeCheckInView. Attendees fragments are there, but not the AttendeesViewModel file that is mentioned in this issue. Will you please help?

**Comment by ShridharGoel** [comment]
https://github.com/fossasia/open-event-organizer-android/blob/development/app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesViewModel.java

**Comment by dipu989** [comment]
@ShridharGoel  This file appears nowhere in my cloned repo. I have followed development setup guide of the project.
Why is that happening?
![Screenshot from 2019-10-14 14-00-05](https://user-images.githubusercontent.com/31280303/66738098-524aa800-ee8b-11e9-8c0f-35d936079ce7.png)

**Comment by dipu989** [comment]
@iamareebjamal @ShridharGoel This file appers nowhere in my cloned repo. I have followed development setup guide of the project. Can't figure out where I did wrong!
![Screenshot from 2019-10-14 14-00-05](https://user-images.githubusercontent.com/31280303/66738362-e9affb00-ee8b-11e9-90ba-e2b644b6ba80.png)

**Comment by iamareebjamal** [comment]
Paste the output of `git log`

**Comment by ShridharGoel** [comment]
Do this: `git pull upstream development`.

**Comment by dipu989** [comment]
@iamareebjamal @ShridharGoel 
Pulling changes from upstream worked! Thanks. Will keep this in mind from the next time!

**Comment by Shhreyya** [comment]
@ShridharGoel I want to work on this.
