### ISSUE TITLE
Illogical way to handle URL in logging in

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-organizer-android#1753]
**Describe the bug**
When user types in other URL in the first fragment, they shouldn't have to type in the URL again

**Screenshots**
<img src="https://i.ibb.co/qxNjFJs/64978371-303912910513414-7852861330049466368-n.jpg" width="300">
<img src="https://i.ibb.co/6w7bFLL/ezgif-2-b499ef29cd3d.gif" alt="ezgif-2-b499ef29cd3d" border="0">

**Would you like to work on the issue?**
Open to all

**Comment by iamareebjamal** [comment]
Save other URL in shared preference
