### ISSUE TITLE
Implement refresh token authentication

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-organizer-android#1857]
API Docs - https://api.eventyay.com

By default, users will not be logged out from the site. All needed info on how to implement it is present in Authentication Section of the API doc above. If any doubt, ask me.

**Comment by theindianappguy** [comment]
Link is not valid anymore, please update

here is the error I can see :
Application Error
The page was not found in the hosted application

Platform Error
The deployment was not found in the infrastructure layer

The deployment could not be found on ZEIT Now.
The deployment could not be found on the platform.

404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: bom1:d6f2m-1576695882264-b7596717127d

If you are a visitor, please try again later.
If you are the owner and this is not expected, please see the developer documentation through the link below for likely causes.

**Comment by iamareebjamal** [comment]
https://api.eventyay.com
