### ISSUE TITLE
Profile picture does not show in navigation drawer until app is reopened

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-organizer-android#1860]
**Describe the bug**
On updating profile picture, it does not show in the navigation drawer until the app is reopened.

**Would you like to work on the issue?**
Open to all.

**Comment by ShridharGoel** [comment]
@iamareebjamal Can you please tell what can be done to fix this? I thought of using LiveData and update the navigation view in `MainActivity` when image gets uploaded but `OrganizerDetailViewModel`  has 'OrganizerDetailActivity` and does not use the `MainActivity` so it's not working that way.

**Comment by iamareebjamal** [comment]
Pull the image in onResme

**Comment by Khali851999** [comment]
> Pull the image in onResme
Would the same thing work for the name feature too?

**Comment by Prashant830** [comment]
I'm working on it
