### ISSUE TITLE
User name not updated on navigation drawer

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-organizer-android#1891]
**Describe the bug**
After changing username infomation, navigation drawer doesn't update it

**Screenshots**
<img src="https://i.ibb.co/D5HYZqn/ezgif-2-a829640c2e90.gif" alt="ezgif-2-a829640c2e90" border="0">

**Would you like to work on the issue?**
Open to all

**Comment by rajput2122** [comment]
I want to fix this issue. Can you please allow me to look after this issue and contribute.

**Comment by anhanh11001** [comment]
Please go ahead

**Comment by rajput2122** [comment]
thanks, sir for this

**Comment by ShridharGoel** [comment]
@rajput2122 Any updates on this?

**Comment by naman653** [comment]
Can I work on this?

**Comment by ShridharGoel** [comment]
@naman653 Yes, go ahead.

**Comment by rahulpansari** [comment]
i would like to work on this issue

**Comment by naman653** [comment]
I am still working on this issue.

**Comment by codedsun** [comment]
@naman653 Any update?

**Comment by iamareebjamal** [comment]
Go ahead @codedsun

**Comment by njnaman** [comment]
Can i work on this issue??

**Comment by codedsun** [comment]
@njnaman i am working on this issue, I got some issues with the app yesterday .
