### ISSUE TITLE
Order summary is inconsistent

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-organizer-android#1898]
**Describe the bug**

The overview section shows 109 tickets sold with 0 USD of transaction but when I open the event it shows 80 tickets sold and 800$ of transaction. This number changes randomly

_Correct Numbers_
![Screenshot_2019-08-18 Overview Tickets FOSSASIA Meetup Events eventyay](https://user-images.githubusercontent.com/25428397/63224069-98adbe80-c1dc-11e9-8797-37c8cf24b713.png)

_Bug_
![WhatsApp Image 2019-08-18 at 4 51 42 PM(1)](https://user-images.githubusercontent.com/25428397/63223955-f0e3c100-c1da-11e9-8986-f01894fe883b.jpeg)

![WhatsApp Image 2019-08-18 at 4 51 42 PM](https://user-images.githubusercontent.com/25428397/63223956-f214ee00-c1da-11e9-8f43-25bd39a2c0a9.jpeg)

**Expected behavior**

The data should be consistent

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Xiomi Redmi Note 5 | 
|Android Version| 8.1.0 | 

**Would you like to work on the issue?**

- [ ] Yes
- [x] No
- Other:

**Comment by ShridharGoel** [comment]
The events list uses `ticketsSold` attribute of the Event model and dashboard uses `analytics.totalAttendees`. 

@shreyanshdwivedi Please check if there is a discrepancy between the values of these two on the server side.

**Comment by ShridharGoel** [comment]
@shreyanshdwivedi Can you please point out the attribute being used on the frontend for the number of tickets?

**Comment by iamareebjamal** [comment]
/order-statistics

Use completed tickets, sales and orders
