### ISSUE TITLE
Speakers count is showing wrong in event

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-organizer-android#1899]
**Describe the bug**

The speakers count being shown is wrong in the event. In the Front End dashboard, it's showing the correct count but not in the app.
Dashboard in eventyay:
![Screenshot from 2019-08-18 17-13-49](https://user-images.githubusercontent.com/21087061/63224001-a7e03c80-c1db-11e9-9964-288907c8265d.png)

Dashboard in app:
![WhatsApp Image 2019-08-18 at 17 09 53](https://user-images.githubusercontent.com/21087061/63224005-b4fd2b80-c1db-11e9-9a9b-eccc75f86c84.jpeg)

**Comment by ShridharGoel** [comment]
The app shows the number of accepted speakers.

@iamareebjamal Should this be changed to the number of confirmed speakers?

**Comment by iamareebjamal** [comment]
Yes

**Comment by iamareebjamal** [comment]
Hope you're using this endpoint - /general-statistics

**Comment by ShridharGoel** [comment]
> Hope you're using this endpoint - /general-statistics

Yes.
