### ISSUE TITLE
Notifications not loading while there are unread notifications on eventyay

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-organizer-android#1902]
**Describe the bug**

No notification is being shown in the app while the eventyay account has two new notifications.
(Tried reloading the app and re-logging in but it didn't change)

Eventyay:-
![Screenshot from 2019-08-18 17-43-16](https://user-images.githubusercontent.com/21087061/63224298-c5afa080-c1df-11e9-8120-4fbbbc124fff.png)

Application:-
![WhatsApp Image 2019-08-18 at 17 46 09](https://user-images.githubusercontent.com/21087061/63224327-11fae080-c1e0-11e9-871a-36d0b56598b2.jpeg)

**Comment by ShridharGoel** [comment]
Not reproducible.

![Notifications](https://user-images.githubusercontent.com/35566748/63224402-59ce3780-c1e1-11e9-947e-c3400a104b27.jpeg)
