### ISSUE TITLE
HTTP 401 error when using production API

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-organizer-android#1907]
**Describe the bug**
HTTP 401 error appears (generally on reopening the app) when `https://api.eventyay.com/v1/` is being used as the base URL.

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by liveHarshit** [comment]
No, just refresh the token.

**Comment by ShridharGoel** [comment]
@liveHarshit Shouldn't this also be implemented? So that if it happens that the token does not get refreshed due to some reason, then the user gets logged out.

**Comment by liveHarshit** [comment]
> So that if it happens that the token does not get refreshed due to some reason, then the user gets logged out.

yes, if okhttp authenticator will give invalid access token after implementing refresh token, then the user should logout.

**Comment by ShridharGoel** [comment]
This is already implemented.

https://github.com/fossasia/open-event-organizer-android/blob/27753c7dc33e2c8ef317d749f50706b9ac15d7d7/app/src/main/java/com/eventyay/organizer/data/auth/AuthHolder.java#L66-L70

**Comment by iamareebjamal** [comment]
Then debug why 401 errors were being shown to the user
