### ISSUE TITLE
Show completed attendees list instead of all

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-organizer-android#1908]
**Describe the bug**
Currently, list of all attendees is being used which contains non-completed orders too.
 
**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by ShridharGoel** [comment]
Server issue: https://github.com/fossasia/open-event-server/issues/6396

**Comment by mariobehling** [comment]
Closing this due to changed app goals.
