### ISSUE TITLE
Action bar title changes to 'false' on going back from Legal option in About Us

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-organizer-android#1923]
**Describe the bug**
Action bar title changes to 'false' on going back from Legal option in About Us section.

**Would you like to work on the issue?**
Open to all

**Comment by codedsun** [comment]
Hey, I would like to pick this up. are you working on this?

**Comment by ShridharGoel** [comment]
@codedsun Go ahead.

**Comment by codedsun** [comment]
I am taking this up!
