### ISSUE TITLE
Make the organizer app optionally partially independent of the server side

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-organizer-android#1926]
**Describe the feature you'd like**

Attendees currently need to register for events on the Open Event frontend and the Organizer app is a lot tied up to the Open Event Ecosystem. I think that while the ecosystem approach is nice, Organizer App should help organizers organize the event with whatever registration platforms they are using currently. This may help build an organizer userbase, and gradually Open Event can try to make those users comfortable with all of the Open Event system. Although this may initially leave some of the other features unusable for those who use this method, it will be solving a use-case of the core problem: which is managing attendees and check-ins.
I think that if userbase and usability increase, developer support should increase as well, and this can be a win-win for both Open Event and organizers.

There are thousands of small & free event organizers around the world, especially in colleges and most of them use Google Forms or normal spreadsheets to keep track of attendee data because it's really easy and popular.

Implementation part:
Organizer app can import and parse an excel sheet, and import attendee details into the database. It will then need to send custom emails with a QR code image and some cautionary instructions to all the attendees through an API. Once done, the app should be able to help check-in all of an event's attendees with minimal or no costs.

This is probably a very unformed idea and may need some tinkering to appeal.

**Screenshots**

NA

**Additional context**

NA

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Since this issue is a discussion/suggestion, and since currently, I am not sure if I'd be able to implement this issue in a short enough time, I am adding the `open-for-all` label in case someone would like to work on it. If maintainers approve, if no one's working and I happen to be able to solve a substantial part, I'll send a PR.

**Comment by iamareebjamal** [comment]
Almost impossible to do technically and way out of scope

**Comment by mishuvs** [comment]
Why is it almost impossible to do technically?

**Comment by iamareebjamal** [comment]
> Organizer app can import and parse an excel sheet, and import attendee details into the database. It will then need to send custom emails with a QR code image and some cautionary instructions to all the attendees through an API.

1. Nobody uses standard columns in spreadsheets. How will it get parsed?
2. Parsing CSVs is hell. Parsing excel sheets is something even the devil does not want to do, it is beyond hell
3. This is a perfect way to create spam. Create a spreadsheet with tons of emails and let the system spam those emails for you. We don't want to become spambots. There's a login and onboarding process for each attendee to prevent this. And simply, nothing can happen if the user does not verify the email
4. How is password going to be generated? The entire workflow of backend, frontend and app will have to be changed for this, allowing users to access the link from email to first set their password and then move ahead
5. If someone wants to actually do this, it'll be much much much simpler to just write a 100 line python script and use the API to do themselves rather than making changes in entire ecosystem

**Comment by mishuvs** [comment]
> 1. Nobody uses standard columns in spreadsheets. How will it get parsed?

1. To successfully allow managing attendees, organizers need only the email addresses. The organizer can either simply remove all the columns other than name and email, or use an instructed 'name' & 'email' column names to allow parsing, similar to what Way2Sms or other SMS campaigning services do. It can also demand the spreadsheets to have only those columns that the organizer app's attendee database schema has.
2. Although the email column can be identified programmatically, it will be too much expectation on the user's side for a unique, free & helping service.

> 2. Parsing CSVs is hell. Parsing excel sheets is something even the devil does not want to do, it is beyond hell

I wish I had the experience to counter this, but I don't. Why exactly is parsing excel hell and why does even the devil not want to do it?

> 3. This is a perfect way to create spam. Create a spreadsheet with tons of emails and let the system spam those emails for you. We don't want to become spambots. There's a login and onboarding process for each attendee to prevent this. And simply, nothing can happen if the user does not verify the email

This reason has weight but
1. The login and onboarding process is simply useless for simple case events. It makes the process cumbersome for genuine events for the fear that a very minor percentage of organizers will be spammers.
2. The organizers will have to verify anyway, allowing to maintain some level of accountability. And SplashThat also probably doesn't require attendees to sign up before emails can be sent, if they can why can't Open Event.
2. Instead of having the users sign up for the service just to prevent them from getting spammed, can't the organizers be required to check a box for terms stating that the users holding the emails in their spreadsheets have in fact wanted to attend an event and have registered through a google form or manually?
3. Accepting a spreadsheet with tons of email would be stupidity, which is why there is supposed to be a limit to the number of attendees (say 100 like Typeform).
4. Why do you think it would not be "much much much simpler" to use a python script for spamming and that spammers will flock to an android event organizer app and manually upload sets of 100 emails spreadsheets from the phone to spam instead of using the existing spamming tools they are using already? It's like building a fire-cracker and fearing it'll be used for nuclear bombings.

> 4. How is password going to be generated? The entire workflow of backend, frontend and app will have to be changed for this, allowing users to access the link from email to first set their password and then move ahead

1. Password for whom?
2. The whole point of allowing excels is to not require attendees to register on the frontend. Why do the backend and frontend need to be in the picture?
3. Can the organizer app simply not email a bunch of users with only the QR code image?
4. Why does the user even need to register for this simple use-case of small events?
5. The attendee wants to attend a free event. The only thing about the attendee in the picture is that the attendee will have an email with a QR code image to show to his organizer to let him in.

> 5. If someone wants to actually do this, it'll be much much much simpler to just write a 100 line python script and use the API to do themselves rather than making changes in entire ecosystem

Using the script to shoot the emails? Good, but how do they check-in attendee with the python script? Where is the need to change the "entire ecosystem"?

**Comment by iamareebjamal** [comment]
I just told you the changes required in entire ecosystem. If you are interested in doing so, go ahead. I don't think anyone else will agree to these changes. I have answers to the questions you have asked, but I have no time to go through each one of them. 

I'll just address one point -

Yes, it would be much easier for spam bots to use excel sheets. Because they have thousands of mailing lists and no, they don't require Organiser App for that. You have worked on this app for 4-5 months and you don't seem to realize that apps don't work on magic. They work on APIs. If there is an API that just takes a mailing list and spams things for them, yes, it would be much easier for them to use it rather than create a python script and deal with a rate limited API to create attendees.

**Comment by iamareebjamal** [comment]
I want to leave this issue open, but I am amazed that someone who worked on the project for so many months is asking question like `The whole point of allowing excels is to not require attendees to register on the frontend. Why do the backend and frontend need to be in the picture?`

**Comment by mishuvs** [comment]
> If they will create attendees using the script, they can check-in users through the app. There is no way on this earth, that the app can check-in and manage users just through an excel sheet. You need a database and API. That's why I said, it is almost technologically impossible to do so

I think **this solution (creating attendees through a script, as we did for testing)** is much better and **should exist for public use**. Besides that, I am not interested in working on a solution that the maintainers don't believe in. Ultimately my own PR won't get merged. 

> Is more of a server issue than organizer app issue (App is just a wrapper for server, and I'm embarrassed I have to tell you this. You were in last year's GSoC)

I had worked mostly on the organizer app. I am not aware of the progress of the server and frontend, which is why I thought of it instead of waiting for the whole ecosystem to be developed (to be honest, they've been in development for quite long now for the progress). I'd have tried to do some things differently instead of out-right copying an existing solution. And I am sorry that you are embarrassed to tell me this because of GSoC. You go ahead to insult for my knowledge, but I think I had worked hard on the assigned tasks about Android project with my skills on android and which is why I was there. I may not have much knowledge about software architecture or project management, but I genuinely cared about a project like this to exist and wanted to initiate a discussion on its possibility.

> Yes, it would be much easier for spam bots to use excel sheets... In short, it is a recipe for disaster

What I meant was that I am almost certain that there are better tools available to spam than this. And that caring for spamming isn't worth not building the solution. But still shorter experience, and I may be wrong so not going to push this any further.

> The more I read into your response, the more I think that it is just an attempt of trolling

I am an avid event organizer and I genuinely wanted to build a solution for this as I face these problems. In fact, I had started contributing to the project for the same reason. At the time I was involved in college events and had thought of a check-in app before realizing that EventBrite and OpenEvent already exist. So this is not an attempt of trolling. Instead, I feel trolled for opening a discussion issue here.

> How can it do it without the server! Without registering them on backend! Without having an attendee ID! Is email sent from magic or API?

I thought that SDKs existed to let users send emails. I may be wrong, and definitely have shorter experience so  I am not going to try to add more explanation to this.

> If your event is that small that you don't need to track the attendees (which is not possible without registering), do you even need an event management platform.

Small events don't mean a small number of registrations. It is possible that 500 people registered for an event with a seating capacity of 50, which is where the organizer would be selecting the few he sees fit. Doing this selection on the frontend would be much more cumbersome than on an excel.

> And no, not all attendees need to register. Just the person buying the ticket needs to.

Many events generally don't have groups going, so I was talking assuming that each attendee is registering one for themselves.

> Can you tell me how you can take money from someone to give them tickets without having their account on the server?

I had mentioned that this is a free events use case.

> Even for free ticket, you want to check in the user. How will it happen if there is no user?

I don't see a problem checking if a QR code is valid, which obviously can be checked from a local database without needing to depend on the backend and only an email service.

---

From the discussion, it seems that I want a much smaller version/solution for this problem to exist, which can simply help small event organizers validate check-ins and ensure that only the people they want to attend are attending, make available the data of those who attended, take excels as inputs and outputs. I think that small events (<100 attendees) would contribute to 80% (random guess) of the total events around the world, and a solution for this will be valued. I also still think that this use case may be able to be covered with just excels and third-party email service APIs/SDKs not requiring the use of a separately owned hosted backend. It might not be doable or feasible to do it in this app, or this ecosystem, but I still have some hope for the solution to work in the light of some questions.

**Comment by mishuvs** [comment]
Also, feel free to close this issue. Should I close it? If you approve I'll open an issue for the script if it's not already present.

**Comment by iamareebjamal** [comment]
> not requiring the use of a separately owned hosted backend

You don't need that. You can use eventyay.com

And feel free to send any PR which helps users in your use case

**Comment by mishuvs** [comment]
Closing this issue, currently as I don't have a clear solution in mind that fits in the Open Event architecture for the problem. Will re-open/can be re-opened/referred to later.
The script issue probably belongs to the server repo.
