### ISSUE TITLE
Last name shows as "null"

### ISSUE THREAD

**Issue by its-himanshu** [fossasia/open-event-organizer-android#1939]
**At the time of signup,Last name field is optional,so if we don't fill this field then it shows last name as null**

**Screenshots**

**Smartphone Info:**

|               | |
|---------------|-|
|Device         ||
|Android Version 6.0|    |

**Additional context**

**Would you like to work on the issue?**

- [-] Yes
- [ ] No
- Other:

**Comment by its-himanshu** [comment]
i would like to work on this issue.

**Comment by liveHarshit** [comment]
> i would like to work on this issue.

Yes please, go ahead.

**Comment by rahulpansari** [comment]
I would like to work on this issue..

**Comment by liveHarshit** [comment]
> I would like to work on this issue..

Can you see the earlier comments?? Please go through https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by Ritesh-Ag** [comment]
@liveHarshit As the issue is not solved yet, so should I work on this issue? If yes, I would love to fix this bug.

**Comment by liveHarshit** [comment]
@its-himanshu What is the status?

**Comment by iamareebjamal** [comment]
@Ritesh-Ag Go ahead. If an issue has no response for 7 days, it's open for anyone

**Comment by Ritesh-Ag** [comment]
@iamareebjamal Okay sir!

**Comment by alokbharti** [comment]
@iamareebjamal, @Ritesh-Ag Is it fixed yet?? If not, I would like to take it as my first issue??

**Comment by Ritesh-Ag** [comment]
@alokbharti Working on it.

**Comment by tusharr-98** [comment]
@iamareebjamal it has been more than 18 days since the issue was last assigned...can you reassign it to me so that I can start working on it

**Comment by iamareebjamal** [comment]
You can work on it
