### ISSUE TITLE
Error during signup while entering password

### ISSUE THREAD

**Issue by Ritesh-Ag** [fossasia/open-event-organizer-android#1943]
**Describe the bug**
 When we signup for the first time and we are asked to enter the password.
So, it says minimum character should be 6. And when we enter 6 digit password, it shows that password should be of minimum 8 characters. 

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by Ritesh-Ag** [comment]
I would love to fix this issue.

**Comment by iamareebjamal** [comment]
Go ahead
