### ISSUE TITLE
Change in profile name does not reflect until the app is reopened

### ISSUE THREAD

**Issue by Khali851999** [fossasia/open-event-organizer-android#1955]
**Describe the bug**
When the name is changed from settings, the change is not reflected in the navigation drawer until the app is reopened.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Account'
2. Click on Profile.'
3. Edit name and then save it.
4. Again open the navigation drawer

**Expected behaviour**
The change should reflect immediately.

**Smartphone Info:**
|  Redmi Y2  | |
| Marshmello 8.1|

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
Revalidate from the API whenever the fragment is open.

**Comment by liveHarshit** [comment]
For reference https://github.com/fossasia/open-event-attendee-android/pull/1918

**Comment by Khali851999** [comment]
@liveHarshit 
So can I start working on the same?

**Comment by liveHarshit** [comment]
> @liveHarshit
> So can I start working on the same?

Yes please. Go ahead.

**Comment by Khali851999** [comment]
@liveHarshit 
Can you guide me as to how it can be done? 
Should I call the `getOrganiser()` in `onResume()` ?

**Comment by liveHarshit** [comment]
> @liveHarshit
> Can you guide me as to how it can be done?
> Should I call the `getOrganiser()` in `onResume()` ?

I'm not familiar with this project's codebase. @ShridharGoel Can help you out. Or you can solve it by yourself. Mentors will review your PR.

**Comment by Khali851999** [comment]
@ShridharGoel can you guide mr through the process?

**Comment by njnaman** [comment]
Can i take this?

**Comment by njnaman** [comment]
@liveHarshit can i take this?

**Comment by liveHarshit** [comment]
@Khali851999 Any updated?

**Comment by iamareebjamal** [comment]
@njnaman Go ahead if there is no update since 7 days of last reply, here it's been 12 days

**Comment by Khali851999** [comment]
I've tried a lot of ways to do this but none worked. I am waiting for some reply from @ShridharGoel or anyone having some expertise.

**Comment by iamareebjamal** [comment]
If we knew the steps of solving the bug, don't you think we would have done it ourselves? It's the contributor's responsibility to search and debug to find the bug. If you have any problem, ask us.

**Comment by ShridharGoel** [comment]
@Khali851999 Try fetching the updated profile name in `onResume()`.

**Comment by njnaman** [comment]
In latest development branch , this issue is already solved.
