### ISSUE TITLE
Profile pic disappear on refreshing account section

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/open-event-organizer-android#1961]
**Describe the bug**
Profile pic disappear on refreshing account section and no profile pic is displayed there.

**To Reproduce**
1. Go to Account
2. Refresh the page
3. You will see the issue

**Expected behavior**
Profile pic should be displayed there if available even after refreshing the page.

**Smartphone Info:**
|Redmi Note 4|
|Nogut 7.0|

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by jay24rajput** [comment]
If no one is working on the issue can I take it up??

**Comment by rishabh-997** [comment]
Can you share a gif , there is no such issue in my device...

**Comment by adiig7** [comment]
Can I take this up?

**Comment by msubham193** [comment]
i can fix it....
