### ISSUE TITLE
When sigining up, last name is optional and when left null , name is shown as "FIRSTNAME null" instead of "FIRSTNAME"

### ISSUE THREAD

**Issue by njnaman** [fossasia/open-event-organizer-android#1965]
**Describe the bug**
When sigining up, last name is optional and when left null , name is shown as "FIRSTNAME null" instead of "FIRSTNAME"

**To Reproduce**
1. Sign up and leave the last name null.
2. Go to navigation drawer.
3. Click on 'accounts'.
4. Check the name on the top of accounts screen.

**Expected behavior**
Name should appear as "FIRSNAME" but it appears aws "FIRSTNAME null".

**GIF**

![NewGIF](https://user-images.githubusercontent.com/43788502/67195376-7459a280-f416-11e9-8e5d-d0993ff6974e.gif)

**Smartphone Info:**
Device - Xiomi Redmi Note 5
Android Version - Oreo 8.1

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by njnaman** [comment]
I would like to work on this issue.

**Comment by batriRahul** [comment]
@iamareebjamal can i take this issue?

**Comment by njnaman** [comment]
@liveHarshit can i take this?

**Comment by liveHarshit** [comment]
> @liveHarshit can i take this?

Go ahead
