### ISSUE TITLE
Replace google places API with Mapbox API

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-organizer-android#1969]
**Describe the feature you'd like**
Documentation: https://docs.mapbox.com/android/plugins/overview/places/

**Would you like to work on the issue?**

Open for all

**Comment by liveHarshit** [comment]
@rob729 @naman653

**Comment by naman653** [comment]
I will work on this issue.

**Comment by liveHarshit** [comment]
> I will work on this issue.

Please go ahead if you can solve it asap.

**Comment by codedsun** [comment]
I am taking this up

**Comment by liveHarshit** [comment]
> I am taking this up

Please ask @naman653, We do not assign same issue to multiple contributors.

**Comment by codedsun** [comment]
@naman653 Can i take this up?

**Comment by naman653** [comment]
@codedsun I am working on this.

**Comment by naman653** [comment]
@ShridharGoel @liveHarshit I found that mapbox is implemented in #1813. So what am I supposed to do to solve the issue.

**Comment by liveHarshit** [comment]
@naman653 Then why it is here:
https://github.com/fossasia/open-event-organizer-android/blob/357085835720ff3d524255c4598853938dd588f6/app/build.gradle#L10

**Comment by naman653** [comment]
I removed the google places API dependency from gradle and the app was working just fine.
https://github.com/fossasia/open-event-organizer-android/blob/357085835720ff3d524255c4598853938dd588f6/app/build.gradle#L162
So maybe it is just an unwanted code. Also, why is [EventeDetailsStepOne.java](https://github.com/fossasia/open-event-organizer-android/blob/357085835720ff3d524255c4598853938dd588f6/app/src/fdroid/java/com/eventyay/organizer/core/event/create/EventDetailsStepOne.java) inside the fdroid package? This file represents step one to create an event. So, why it is not in the folder where files corresponding to other steps reside.

**Comment by iamareebjamal** [comment]
https://developer.android.com/studio/build/build-variants

**Comment by liveHarshit** [comment]
> I removed the google places API dependency from gradle and the app was working just fine.

Then remove it.

**Comment by naman653** [comment]
@liveHarshit play store release of the app is using google places API. That's why that code is there. The PR is failing the tests due to this. But I am not seeing play store version in my setup. What should I do?

**Comment by liveHarshit** [comment]
> @liveHarshit play store release of the app is using google places API. That's why that code is there. The PR is failing the tests due to this. But I am not seeing play store version in my setup. What should I do?

Change build variant from FDroid to PlayStore.
