### ISSUE TITLE
Redirect to Dashboard fragment instead of EventList Fragment on pressing back.

### ISSUE THREAD

**Issue by rishabh-997** [fossasia/open-event-organizer-android#1988]
**Describe the feature you'd like**
When the user selects an event from the event list, he is taken to the dashboard fragment. Now if the user selects faq from navigation drawer and presses back after seeing faq, he is taken to event list fragment rather than Dashboard fragment. He again has to select the event from the list. Usually for the user, after selecting an event, he will think he is redirected to a new page, where if he selects any activity from Drawer,  then on pressing back, he will be redirected to dashboard. Redirecting to the list page gives an uneasy user experience.

**Screenshots**
![gif to the feature](https://media.giphy.com/media/eKTzLflqJ4Ov9wc3Qt/giphy.gif)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- [ ] Other

**Comment by rishabh-997** [comment]
@ShridharGoel @iamareebjamal  do you think this feature should be implemented or not ???
Will work on it accordingly...

**Comment by iamareebjamal** [comment]
I agree with this and this was the existing behaviour before the implementation was made to be changed from above

**Comment by rishabh-997** [comment]
> I agree with this and this was the existing behaviour before the implementation was made to be changed from above

On it !!!

**Comment by iamareebjamal** [comment]
Not on it. It should stay the same

**Comment by rishabh-997** [comment]
> I agree with this and this was the existing behaviour before the implementation was made to be changed from above

Sir are you agreeing with the current scenario or with my proposed scenario.

**Comment by iamareebjamal** [comment]
Your proposed scenario was already done in past and was the default behaviour and I agreed with it. But the requirements were changed to make it like the current scenario. So, I don't agree with the current scenario but it is working as intended

**Comment by rishabh-997** [comment]
should i close this issue ?
