### ISSUE TITLE
Update PlayStore Build

### ISSUE THREAD

**Issue by NishithP2004** [fossasia/open-event-organizer-android#1991]
**Describe the feature you'd like**

Currently the PlayStore app is just a normal app with a login page and profile section.
**Screenshots**

![Screenshot_2019-12-07-21-06-25-450_com eventyay organizer](https://user-images.githubusercontent.com/34577844/70383794-baa09c00-1999-11ea-9f1b-8893b95a0a65.jpg)
![Screenshot_2019-12-07-21-13-44-999_com eventyay organizer](https://user-images.githubusercontent.com/34577844/70383795-baa09c00-1999-11ea-8386-fd11565e5a0f.jpg)

**Additional context**

There is no option to create an event or anything else (QR code scanner,etc).
It would be great if the Development app features can be put up as a Beta feature in the Play Store.
**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
There is QR code scanner, and we don't want to give option to create events in the app

**Comment by iamareebjamal** [comment]
You have to understand the goals of the app and the ecosystem before raising issues. Just because the app can't create events doesn't mean it's useless and you can't create events from anywhere. Read a bit about open event and README. It'll help in future

**Comment by NishithP2004** [comment]
> There is QR code scanner, and we don't want to give option to create events in the app

But there is no QR Code scanner option as well in the Play Store release.
Please refer
![Screenshot_2019-12-07-21-13-44-999_com eventyay organizer](https://user-images.githubusercontent.com/34577844/70385822-d9615b80-19b6-11ea-89bf-50e214fed669.jpg)

**Comment by NishithP2004** [comment]
> You have to understand the goals of the app and the ecosystem before raising issues. Just because the app can't create events doesn't mean it's useless and you can't create events from anywhere. Read a bit about open event and README. It'll help in future

Will keep in mind in future
Thanks :)

**Comment by iamareebjamal** [comment]
> But there is no QR Code scanner option as well in the Play Store release.

There is. You need to have events to use it
