### ISSUE TITLE
not being able to use app

### ISSUE THREAD

**Issue by ShaterStar** [fossasia/open-event-organizer-android#1993]
**Describe the bug**
When you first download the app. U can't use any of it features. The + icon to create a new event doesn't exist. It only worked after I enabled developer mode in settings.

**To Reproduce**
 unable to do anything

**Expected behavior**
After downloading I should have been able to make a new event or something.

**Smartphone Info:**
|               | |
|---------------|-|
|Device         ||
|Android Version|   

**Would you like to work on the issue?**

- [x] No

**Comment by ShridharGoel** [comment]
That is the desired behaviour currently. Event creation feature is only in the developer mode. Events can also be created through the website.

**Comment by ShaterStar** [comment]
Alright. Thanks for informing me.

**Comment by iamareebjamal** [comment]
And please look at closed issues before raising new ones. At least 5 people have raised the same issue by now
