### ISSUE TITLE
Displaying Error On Verification of Email

### ISSUE THREAD

**Issue by aryanguls** [fossasia/open-event-organizer-android#1994]
**Describe the bug**
On opening an account on the Eventyay Attendee App it requests an email verification for the account so opened and to do so a link is sent to the registered email. But on clicking the link it redirects to a web page which prints ERROR on the screen. 

**To Reproduce**
1. Go to the Eventyay App.
2. As you open the app it asks for your email.
3. This is followed by  setting up of your account (eg: name , password etc.)
4. After doing so you will recieve a verification email on the registered account.
5. On clicking the link you will see the error message displayed on a web page.(Screenshots provided below)

**Expected behavior**
From my experience of using other applications i expected the application to give a confirmation message on the web page and then redirect me to the application. 

**Logs**

**Screenshots**
![Screenshot (133)](https://user-images.githubusercontent.com/58459496/70441881-347c7680-1abb-11ea-9c4f-bb7be4296aa4.png)

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by ShridharGoel** [comment]
You have opened this issue in the Organizer App repo and then mentioned Attendee App in the description while the issue actually belongs to the frontend.

**Comment by ShridharGoel** [comment]
Please open the issue on the frontend repo.
