### ISSUE TITLE
profile bug

### ISSUE THREAD

**Issue by DariusNasta13** [fossasia/open-event-organizer-android#1995]
**Describe the bug**
When i want to see my profile the app ask me if i want to log out

**To Reproduce**
The app ask if i want to log out

**Expected behavior**

**Logs**

**Screenshots**

![78546044_497940387483127_737549917421043712_n](https://user-images.githubusercontent.com/58443232/70449643-fd9e6480-1aaa-11ea-93f1-6300ad9b666d.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
Device    Samsung Galaxy S8
Android Version   9

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [x] No
- Other:

**Comment by liveHarshit** [comment]
We're following Eventbrite.
