### ISSUE TITLE
Alignment of "Time Interval" dropdown ;Addition of 'back' button and colour contrast of instrument screen

### ISSUE THREAD

**Issue by PicantaData** [fossasia/open-event-organizer-android#1996]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**Smartphone Info:**

|               | |
|---------------|-|
|Device         ||
|Android Version|    |

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by PicantaData** [comment]
Hey!
It was by mistake that I submitted the issue empty!
I was editing it when you just closed it!

**Comment by iamareebjamal** [comment]
I closed it because it is not the correct repo for your issue. Read before creating issues
