### ISSUE TITLE
Add a Guideline or a tutorial 

### ISSUE THREAD

**Issue by kumuditha-udayanga** [fossasia/open-event-organizer-android#1997]
**Description**
* When I launch the app I don't know what to do with this app because there is no small tutorial, small video clip or a description of how to use this app.
* And also according to my experience, some of the core features of this app isn't working for example(Event creation/Ticket Creation)

# Screenshots
*About Us
![About us](https://user-images.githubusercontent.com/27630091/70459391-183c0200-1ada-11ea-8187-28a0a4ad100e.jpeg)

* First Page
![First Page](https://user-images.githubusercontent.com/27630091/70459502-520d0880-1ada-11ea-89bf-73e49ed242b4.jpeg)
 
**Additional context**
* So I would recommend adding a tutorial or a description how to use this application.
* And to resolve the non-working core features of the app.

**Would you like to work on the issue?**

- [ ] Yes
- [ * ] No
- Other:

**Comment by iamareebjamal** [comment]
The app is for organizers of open event platform. If you know what it is, you know how to use the app. If you don't, you don't need the app

**Comment by iamareebjamal** [comment]
Those features are developer only and enabled when you build the app from source
