### ISSUE TITLE
unread notification even after there is no new notification

### ISSUE THREAD

**Issue by jayant218** [fossasia/open-event-organizer-android#1999]
**Describe the bug**
the notification icon on the home page always shows new notification, even if there is no new notification. 
**To Reproduce**
1. Read all notification from the notification page, so that there is no unread notification.
1. Now, go to any other page of the app from the homepage
3. Now again go to the homepage.
4. There you can see an active notification(unread notification).
5. But as soon as you enter the notification page there is no new notification

**Expected behavior**
The notification icon should be marked only when there is any unread notification

**Smartphone Info:**
|Device         |Samsung Galaxy S7|
|Android Version|Oreo 8.0|

**Would you like to work on the issue?**

- 

- [x] Yes
- [ ] No
- Other:

**Comment by jayant218** [comment]
> **Describe the bug**
> the notification icon on the home page always shows new notification, even if there is no new notification.
> **To Reproduce**
> 
> * [1] Yes
> * [x]  No
> * Other:

**Comment by ankit2019j** [comment]
can you please describe this issue more like attach a screenshot or something
