### ISSUE TITLE
Profile picture does not apper in side bar thing

### ISSUE THREAD

**Issue by aRealCyborg** [fossasia/open-event-organizer-android#2000]
I changed my profile picture and it took a few times to actually change it. 
But when you open up the side bar that allows you to see the settings, your account and about your org, it does not appear in the pfp spot there.

**Comment by rishabh-997** [comment]
it depends on your internet speed. No such issue arises in my phone.

**Comment by chourasiaamit** [comment]
No issue is not solved my internet speed is good but still I can't see my profile image on side bar

**Comment by Shhreyya** [comment]
I can work on this issue.

**Comment by Prashant830** [comment]
Can I solve this issue

**Comment by msubham193** [comment]
can i work on this issue...
