### ISSUE TITLE
Multiple CreateEventActivities open on multiple taps

### ISSUE THREAD

**Issue by Kalit31** [fossasia/open-event-organizer-android#2007]
**Describe the bug**
Multiple CreateEventActivity open up when the add('+') is pressed multiple times simultaneously.
Similar bug is found on tapping the profile icon(found in navigation drawer) multiple times.

**To Reproduce**
1. Go to the App
2. Tap on add Event button or the profile icon multiple times.
3. Now, as you press the backPress button, you land up in CreateEvent Activity or Profile Activity
 respectively depending on what you tap.

**Expected behavior**
You should have reached the home screen instead of the CreateEvent Activity.

**Logs**

**Screenshots**

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung Galaxy J8|
|Android Version|Pie 9.0|

**Additional context**

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by anushruti11** [comment]
I wanna work on this issue.Please assign it to me.

**Comment by shubhamofbce** [comment]
@Kalit31 Any updates on this issue ??
