### ISSUE TITLE
App didnt contain any vedio please update your app

### ISSUE THREAD

**Issue by Siva-Siddarth-Reddy** [fossasia/open-event-organizer-android#2011]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**Smartphone Info:**

|               | |
|---------------|-|
|Device         ||
|Android Version|    |

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by adityastic** [comment]
@iamareebjamal
