### ISSUE TITLE
Reimplement event sales stats

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-organizer-android#2020]
Since revenue, tickets sold, tickets available have been removed from the API, app sales info is broken and needs to be reimplemented

https://github.com/fossasia/open-event-organizer-android/pull/1315

**Comment by iamareebjamal** [comment]
@codedsun Can you take this up please

**Comment by codedsun** [comment]
Okay, taking

**Comment by codedsun** [comment]
@iamareebjamal - For the revenue I can get in https://open-event-api-dev.herokuapp.com/v1/events/9/order-statistics 

Response: ` {"data": {"type": "order-statistics-event", "attributes": {"sales": {"total": 200.0,`


But for tickets- i had to get the tickets via
/v1/events/9/tickets

and suppose if the event has multiple ticket - then fetch these ticket details in a loop with ticket-is

like `/v1/tickets/27/order-statistics` 

correct?

**Comment by iamareebjamal** [comment]
They should be available there

**Comment by codedsun** [comment]
@iamareebjamal 

The event statics shows this as response. We dont have total quantity of tickets.


```
{
    "data": {
        "type": "order-statistics-event",
        "id": "38",
        "attributes": {
            "orders": {
                "total": 25,
                "draft": 0,
                "cancelled": 0,
                "pending": 0,
                "expired": 20,
                "placed": 2,
                "completed": 0
            },
            "sales": {
                "total": 250.0,
                "draft": 0,
                "cancelled": 0,
                "pending": 0,
                "expired": 200.0,
                "placed": 20.0,
                "completed": 0
            },
            "tickets": {
                "total": 31,
                "draft": 0,
                "cancelled": 0,
                "pending": 0,
                "expired": 26,
                "placed": 2,
                "completed": 0
            },
            "identifier": "95a16dad"
        },
        "links": {
            "self": "/v1/events/38/order-statistics"
        }
    },
    "links": {
        "self": "/v1/events/38/order-statistics"
    },
    "jsonapi": {
        "version": "1.0"
    }
}
```

**Comment by iamareebjamal** [comment]
Then what is this?

```
"tickets": {
                "total": 31,
```

**Comment by codedsun** [comment]
@iamareebjamal  - it's not the total quantity of tickets which can be ordered.

From the codebase it says
`total = db.session.query(func.sum(OrderTicket.quantity.label('sum'))).join(Order.order_tickets).filter(
            OrderTicket.ticket_id == obj_id).scalar()`


Actual ticket capacity is different

![image](https://user-images.githubusercontent.com/20026440/71730202-8ff61600-2e67-11ea-895b-07c788946957.png)

**Comment by iamareebjamal** [comment]
Yeah, then add them in event statistics

**Comment by codedsun** [comment]
Okay, then will raise the issue on server side. Thanks

**Comment by iamareebjamal** [comment]
Same issue, no need of creating new one

**Comment by codedsun** [comment]
@iamareebjamal  - What should be the structure like when there are multiple tickets? 

I should add them under `http://127.0.0.1:5000/v1/tickets/30/order-statistics` but then again the client has to call this API for all the unique ticket available .? 

Am I Corrrect?

**Comment by iamareebjamal** [comment]
?

**Comment by codedsun** [comment]
@iamareebjamal  - The ticket quantity is not present under http://127.0.0.1:5000/v1/tickets/30/order-statistics 
 as discuessed here. (https://github.com/fossasia/open-event-organizer-android/issues/2020#issuecomment-570595585)

You asked me to add under this, but how do I do this when there are multiple tickets like (Paid, Free etc) shall I return just the sum of them in this api?

or shall I add this under `http://127.0.0.1:5000/v1/tickets/30/order-statistics ` with respect specific ticket id?

**Comment by iamareebjamal** [comment]
I asked to add under general-statistics. 

> but how do I do this when there are multiple tickets like (Paid, Free etc)

See what's required in app. You're looking at screenshot of frontend and that too of order sales, not ticket count, about which the discussion was going on

**Comment by codedsun** [comment]
@iamareebjamal - I mean that 
`revenue, tickets sold, tickets available`  this is required in the app as they are removed from the api.
` https://open-event-api-dev.herokuapp.com/v1/users/31/events?page[size]=0`

SS for the app:


![](https://user-images.githubusercontent.com/23634977/44049790-b619ba3a-9f52-11e8-8498-1b65c730d704.png)



Now as I want these - I will have to hit 

1. For all the events of user - ` https://open-event-api-dev.herokuapp.com/v1/users/31/events?page[size]=0`
2. For revenue of each event - `https://open-event-api-dev.herokuapp.com/v1/events/9/order-statistics ` 
example: "sales": {"total": 200.0,

3. For ticket-count of each event - 
`https://open-event-api-dev.herokuapp.com/v1/events/9?include=tickets` 

 I am hitting extra 2 calls to get the revenue and ticket-counts.

Which mean  If a user has 10 events  - then 20 calls just for this screen.

**Comment by iamareebjamal** [comment]
First you were talking about multiple tickets types and free and paid tickets and whatnot and now you're talking about multiple API calls. Can you please stick to 1 thing in a discussion?

You don't need ?include=tickets for ticket count. Add that info in order statistics and include order-statistics with events

https://open-event-api-dev.herokuapp.com/v1/users/31/events?page[size]=0&include=order-statistics

1 call for just this screen

**Comment by codedsun** [comment]
@iamareebjamal  - I am sorry.

>  Add that info in order statistics and include order-statistics with events 

I will add the info (ticket_quantity) under `order-statistics`.

I got this.

Now, 

my first ques(https://github.com/fossasia/open-event-organizer-android/issues/2020#issuecomment-570773207)  - 

` but how do I do this when there are multiple tickets like (Paid, Free etc) shall I return just the sum of them in this api?`

Explain - If i had multiple tickets 
Paid -  Ticket quantity =100
Free - Ticket quantity = 200

Then I shall return `ticket_quanity` as 300  = sum of (paid+free)

Am I clear this tym?

**Comment by iamareebjamal** [comment]
Why do you need to separate free and paid tickets? Is there a UI in the app where it is needed?

**Comment by codedsun** [comment]
I don't need to seperate, I am asking about the case here - When there are multiple tickets in an event then I have to take their quantity count also.

**Comment by codedsun** [comment]
I have not mentioned anywhere of seperating- 
For an event - 
the ticket quantity count should be equal to sum of all the possible tickets ticket quanity (be it paid, dontation, free)

More specific - this is what I am talking about 

![image](https://user-images.githubusercontent.com/20026440/71765255-44e80b80-2f18-11ea-87ff-825085f5a5f9.png)

**Comment by iamareebjamal** [comment]
Yes
