### ISSUE TITLE
Suggest a feature

### ISSUE THREAD

**Issue by rajat-png** [fossasia/open-event-organizer-android#2024]
one feature i suggest you to create a option "RATE US"
Better than "RATE US" feature.

**Comment by vs4862876** [comment]
Hello.I have spent a lot of time on the App. And fond a minor mistake that App is in single colour that is red.It should be in different colours to attract users.I would love to see an instrument to that can count the number of steps.Descriptions of guide should be more deatailed.It should be user friendly.

**Comment by Sid911** [comment]
I think new rating system should be added like Google Maps etc. so that people can get prompted once about rating the application

**Comment by iamareebjamal** [comment]
@vs4862876 There is not a single place in the app where the color RED is used. Don't know if red is same around the world, but here, it refers to the part of visible light with lowest frequency and highest wavelength
