### ISSUE TITLE
Please upload some vedios in this app for more information

### ISSUE THREAD

**Issue by siva-siddartha-reddy-5377** [fossasia/open-event-organizer-android#2028]
**Describe the feature you'd like**

**Screenshots**

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
Don't spam the issue boards with invalid issues

**Comment by siva-siddartha-reddy-5377** [comment]
Ok sorry please forgive
