### ISSUE TITLE
Bug report for PSLab Android app

### ISSUE THREAD

**Issue by Shreyanshsaboo** [fossasia/open-event-organizer-android#2043]
1. some of the measuring types of equipment( like Oscilloscope) are horizontal and cannot be worked if the mobile phone is kept vertical.

2.  Some of the measuring types of equipment( like barometer) work but show a message that it is not installed in your phone.

**Comment by dheerajkotwani** [comment]
**This Repo is of Open Event Organiser App**
Give the issues of PSLab in https://github.com/fossasia/pslab-android/issues

**Comment by iamareebjamal** [comment]
If only people could read
