### ISSUE TITLE
bug: EditText for Name in Edit Profile

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/open-event-organizer-android#2048]
**Describe the bug**
In the edit profile fragment while entering name and clicking enter changes the line but name should be entered in single line and it should focus to next edit text

**To Reproduce**
1. Go to Edit Profile
2. Enter some name
3. Click Enter

**Expected behavior**
Clicking enter should make focus on next edit text

**Screenshots**
![Screenshot_2020-01-23-02-32-40-349_com eventyay organizer](https://user-images.githubusercontent.com/44086235/72934195-33f92000-3d89-11ea-8cd8-998c4e57612c.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi Note 4|
|Android Version|Nougat 7.0|

**Additional context**
No

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by SunitRoy2703** [comment]
I'm working on this

**Comment by Prashant830** [comment]
Can I solve this problem
