### ISSUE TITLE
bug: Scrolling in Edit profile

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/open-event-organizer-android#2050]
**Describe the bug**
While Scrolling the Edit Profile layout in landscape mode the content hides behind the Done buttoon

**To Reproduce**
1. Go to Edit Profile
2. Change to landscape mode
3. Scroll down to bottom

**Expected behavior**
The date should scroll above  the button

**Screenshots**
![bug_edit_profile_scroll](https://user-images.githubusercontent.com/44086235/73104682-fc22e180-3f1c-11ea-8f1c-a0b3ee2e157c.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi Note 4|
|Android Version|Nougat 7.0|

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by bipul144** [comment]
I like to work in it

**Comment by dheerajkotwani** [comment]
The issue already contain a pr.

**Comment by Prince-kushwaha** [comment]
what this issue is solved or not

**Comment by YugN17** [comment]
@mariobehling @dheerajkotwani  can i work on this issue???

**Comment by iamareebjamal** [comment]
Take one issue at a time

**Comment by YugN17** [comment]
@iamareebjamal yes i am taking this one

**Comment by Prince-kushwaha** [comment]
I want to work on this issue

**Comment by Prashant830** [comment]
Can I solve this problem?
