### ISSUE TITLE
Only Strong Password must be allowed only for Sign Up and Whitespace must not be allowed in beginning and in the end of password

### ISSUE THREAD

**Issue by Bhawna11agg** [fossasia/open-event-organizer-android#2053]
**Describe the bug**
While entering a password there must be a check for a strong password and whitespace must not be allowed at the starting and end of the password.

**To Reproduce**
1. Go to Sign Up Page
2. Click on Password
3. Enter 8 Whitespaces and it is accepting

**Expected behavior**
Only strong passwords must be allowed to be accepted as a mixture of numbers, special characters, Alphabets.

**Smartphone Info:**
Device: Asus Zenfone M1 pro 
Android Version: Oreo 8.1 

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
Your definition of a strong password is seriously flawed and this is the job of a server
