### ISSUE TITLE
Change Password Activity should contain Forget Password option

### ISSUE THREAD

**Issue by Bhawna11agg** [fossasia/open-event-organizer-android#2054]
**Describe the feature you'd like**
As if the user wants to change the password but he did not remember then it will create inconvenience for him. 

**Screenshots**
![image](https://user-images.githubusercontent.com/47032273/73125261-7f087280-3fd7-11ea-89de-57c5a60d4adc.png)

**Would you like to work on the issue?**
Yes

**Comment by Bhawna11agg** [comment]
Can I work on this?

**Comment by adiig7** [comment]
I want to work on this. Can I?

**Comment by anushruti11** [comment]
Can I work on this?

**Comment by KartikSoneji** [comment]
@Bhawna11agg 
@adiig7 
@anushruti11 

Needing the old password to set the new one is a standard security feature.
This **should never** be implemented.
For a more thorough explaination and some unique scenarios, I encourage you to read this post:
https://security.stackexchange.com/questions/162021/what-is-the-purpose-of-confirming-old-password-to-create-a-new-password

@fossasia Can this issue please be closed?

**Comment by shubhamofbce** [comment]
@Bhawna11agg How are you going to solve this issue?? If you are planning to remove the Old password field then it is a serious issue.You can't do this but If you can think of some other innovative way to do the same then please share that ??

**Comment by Shhreyya** [comment]
I want to work on this issue.
