### ISSUE TITLE
bug: Date Time Input Text Alignment

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/open-event-organizer-android#2055]
**Describe the bug**
Date and Time Input Text are not aligned properly in Create New Event

**To Reproduce**
1. Go to Create New Event
2. Scroll down to Date and Time
3. Uncheck Use Picker

**Expected behavior**
Date Time Edit Text must be aligned properly

**Screenshots**
![Screenshot_2020-01-26-11-18-05-581_com eventyay organizer](https://user-images.githubusercontent.com/44086235/73131292-8149eb80-402e-11ea-8ad0-2c2bfa11a3a5.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi Note 4|
|Android Version|Nougat 7.0 |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by ankushmundhra** [comment]
@dheerajkotwani i want to work on this.

**Comment by dheerajkotwani** [comment]
go ahead @ankushmundhra

**Comment by sanjulamadurapperuma** [comment]
This issue can be closed now right? Since the fix seems to have been merged already.
