### ISSUE TITLE
datetime edit text is too complex to understand.

### ISSUE THREAD

**Issue by ankushmundhra** [fossasia/open-event-organizer-android#2058]
**Describe the bug**
The datetime edit text in the create event activity shows the date time in a format that is too complex for a common man to understand. 

**To Reproduce**
1. Go to Create New Event
2. Scroll down to Date and Time
3. Uncheck Use Picker
4. See the bug

**Expected behavior**
The datetime format should be easy to understand.

**Screenshots**
![Screenshot_20200127_175708_com eventyay organizer](https://user-images.githubusercontent.com/44394901/73179096-a296fe80-4138-11ea-8285-e8cca975eb1c.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Honor 8 pro|
|Android Version|Pie 9.0|

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by ankushmundhra** [comment]
@iamareebjamal Should i work on this issue?

**Comment by saketsingh0078** [comment]
i want to work in this issue

**Comment by iamareebjamal** [comment]
Not needed

**Comment by KartikSoneji** [comment]
@iamareebjamal 
> Not needed

This seems like a good improvement to me.
"too complex for a common man" is a bit of an exaggeration, but the date can be displated in a nicer format.
Something like:
```
27 Jan 2020  17:56  +5:30 (IST)
```
Was there a particular reason for the issue to be closed?

**Comment by iamareebjamal** [comment]
Yes, we already provide date picker for "common man". The checkbox is for advance users and stores datetime in ISO8601 format. There is neither a reason to show it in `27 Jan 2020  17:56  +5:30 (IST)` format nor a way to parse it as such when there already is a date time picker for others
