### ISSUE TITLE
bug: previous button disappear while creating event

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/open-event-organizer-android#2059]
**Describe the bug**
While creating any event if we change the orientation to landscape mode in Step 2 or Step 3 then Previous button gets disappeared from the screen

**To Reproduce**
1. Go to Step 2 of Create Event
2. Change orientation to landscape mode
3. Change orientation again to portrait mode

**Expected behavior**
The previous button should not get diappeared on orientation change

**Screenshots**
![issue_pev_but_dis](https://user-images.githubusercontent.com/44086235/73212228-c9265b00-4173-11ea-8f16-58781bf615ae.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi Note 4|
|Android Version|Nougat 7.0|

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by nulllpointerexception** [comment]
i am working on this
