### ISSUE TITLE
bug: pressing enter to change line

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/open-event-organizer-android#2060]
**Describe the bug**
On pressing Enter in name while Creating Events or in Organiser Name take to a new line.

**To Reproduce**
1. Go to  Create Event 
2. Click on Name of Event
3. Press enter

**Expected behavior**
On pressing enter in name it should point to next input field

**Screenshots**
![issue_name](https://user-images.githubusercontent.com/44086235/73212684-beb89100-4174-11ea-9552-ce4ef766251e.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi Note 4|
Android Version|Nougat 7.0|

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by nulllpointerexception** [comment]
@liveHarshit  can i work on this ?

**Comment by souravshine** [comment]
Can I work in this
