### ISSUE TITLE
feat: add hint to know about different privacy in speaker create

### ISSUE THREAD

**Issue by 991rajat** [fossasia/open-event-organizer-android#2064]
**Describe the feature you'd like**
**Add hint (As ex. public,private) to know about different privacy in the speaker call create.
It will be helpful to know about different privacy.** 

**Screenshots**

![Screenshot_20200130-202347](https://user-images.githubusercontent.com/38184186/73460872-35d16d80-439f-11ea-8042-05512371ff98.png)
**Would you like to work on the issue?**

- [x] Yes

**Comment by 991rajat** [comment]
YES

**Comment by iamareebjamal** [comment]
Explain

**Comment by 991rajat** [comment]
Privacy is public and private. What if people don't know and enter anything randomly.
The hint will tell the options they have. 
Like Privacy (ex. public, private)

**Comment by 991rajat** [comment]
@iamareebjamal Do you feel this issue relevant or helpful? Or Should I close it?

**Comment by iamareebjamal** [comment]
Make it a dropdown

**Comment by mariobehling** [comment]
out of scope. We need to focus on basic feature parity with website for now.
