### ISSUE TITLE
bug: privacy text view hide behind button

### ISSUE THREAD

**Issue by 991rajat** [fossasia/open-event-organizer-android#2067]
**Describe the bug**
Due to no presence of a margin-bottom privacy text view hide behind the button.
Scrolling won't help here to reach to privacy text view.

**To Reproduce**
1. Go to Speaker Call Create
2. Change Orientation
3. Scroll down 
4. See bug

**Expected behavior**
Margin Bottom required for proper scrolling.

**Screenshots**

![Screenshot_20200131-100711](https://user-images.githubusercontent.com/38184186/73513138-4bcc4600-4412-11ea-8297-9ff48b89919f.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |[Moto E2]|
|Android Version|[Nougat 7.1.2]    |

**Would you like to work on the issue?**

- [x] Yes

**Comment by adiig7** [comment]
@mariobehling please assign it to me.

**Comment by vennelakoilada362** [comment]
I want to work on this issue, please assign it to me 
I want to contribute on this issue and guide me though this

**Comment by Prashant830** [comment]
I've solved it, can I hit a PR?
