### ISSUE TITLE
Delete icon appearing even after profile picture deleted

### ISSUE THREAD

**Issue by dipu989** [fossasia/open-event-organizer-android#2072]
**Describe the bug**
An option to delete the image is always there even after the image has been deleted.

**To Reproduce**

1. Go to your profile and upload a profile picture
2. Delete the picture

**Expected behavior**
There should be no option as such to delete the image after it's been deleted.

**Would you like to work on the issue?**
Open to all

**Comment by dheerajkotwani** [comment]
I would like to work on it

**Comment by codesurf** [comment]
My team of computer science pursuing members would like to work upon resolving this issue.

**Comment by deepak-prajapatii** [comment]
@dipu989 Can I work on this issue?
