### ISSUE TITLE
In App change language feature in settings

### ISSUE THREAD

**Issue by rishabh-997** [fossasia/open-event-organizer-android#2073]
**Describe the feature you'd like**
In the settings page, there must be a spinner through which we can change the language of app from the language list available

**Screenshots**

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by rishabh-997** [comment]
Should I work on this @iamareebjamal sir ???

**Comment by rishabh-997** [comment]
![Screenshot_20200211-112803_1](https://user-images.githubusercontent.com/45125121/74214027-c07c6b80-4cc1-11ea-9ff4-6013163a5c59.jpg)
Something like this

**Comment by Muskan-2403** [comment]
Sir, can i work on this? @iamareebjamal @mariobehling

**Comment by rishabh-997** [comment]
> Sir, can i work on this? @iamareebjamal @mariobehling

Which language are you intending to add in the app?

**Comment by Muskan-2403** [comment]
> > Sir, can i work on this? @iamareebjamal @mariobehling
> 
> Which language are you intending to add in the app? 

Hindi
