### ISSUE TITLE
Create dark mode

### ISSUE THREAD

**Issue by rishabh-997** [fossasia/open-event-organizer-android#2074]
**Describe the feature you'd like**
It would be great if there is dark mode feature in app as well
*Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by rishabh-997** [comment]
I am planning to use DayNight theme of material theme

[Day Night Theme](https://material.io/develop/android/theming/dark/)

@iamareebjamal sir ???

**Comment by adityastic** [comment]
@rishabh-997 it's very difficult to maintain dark mode and translations

**Comment by iamareebjamal** [comment]
Not a priority

**Comment by mariobehling** [comment]
No need, out of scope in this project. Therefore closing it.
