### ISSUE TITLE
Not able  to Upload Image on Account Activity . Empty Snackbar being displaying.

### ISSUE THREAD

**Issue by nileshteji** [fossasia/open-event-organizer-android#2104]
While testing the Application I was not able to upload a new image  . After some time of Uploading the image, an empty snackbar is Displayed. There can be two bugs  in this thing:

1. If we are able to upload the image to the server , the Image is not being shown on the imageView, and also an empty snackbar is displayed.
2. There can be one more test case If the image is not being uploaded , there should be an error message which should be displayed on the snackbar.

**Reproduce the test cases**
1. Go to the Navigation Drawer 
2. Click on the imageView on the Top Left. This prompts you to the Account Activity 
3. Click on the imageView present at the Account Activity 
4. Choose an image to upload 
5. The Image will not be uploaded to the server and set to the imageView 
6. Empty Snackbar appears after 5-10 secs of uploading of image 

**Expected behavior**
The Behaviour should be as follows:-
1. We should be able to upload the image to the server with imageView being replaced with the new image.
2. If there is an error we should get a snackbar with required details

**Screenshots**
I am Providing with link of Screen Record which will help to visualize the bug more  effectively 
https://drive.google.com/file/d/1pgiDvwhrOvaZ4h2Vo47dzhGaDiNUfEWc/view?usp=sharing

**Smartphone Info:**
Device: One plus 5
Android Version: Android 9

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by adiig7** [comment]
Can I work on this?

**Comment by liveHarshit** [comment]
@adiig7 go ahead

**Comment by shreyashcode** [comment]
@adiig7 are you working on it??

**Comment by siddhantdrk** [comment]
@liveHarshit can I work on it ??
