### ISSUE TITLE
Adding Save Button in the Edit Profile 

### ISSUE THREAD

**Issue by nileshteji** [fossasia/open-event-organizer-android#2105]
**Describe the feature you'd like**
There is no Save button in the Account activity which lets you change the updates of your account. Alert Dialog similar to Edit Profile(Screenshot attached below should be added to the account back press 

**Screenshots**

Link for the UI Mockup
[Images](https://drive.google.com/folderview?id=1puj2jYBeum5m29GP3YzENO9grnZHro7g) for the UI Mockup. We should add an alert dialog similar to Edit Profile dialog in the account activity 

[Video](https://drive.google.com/file/d/1psypf4VCUKNRr5rFmdMQKpNR7A2But5r/view?usp=sharing) to provide better visualization of the feature

This issue can be related to [issue](https://github.com/fossasia/open-event-organizer-android/issues/2104#issue-622344780).

**Additional Context**
With the help of this issue we will update the image of the User only one it prompts us to the save button. So when the user picks the image from the gallery it will only be updated at the imageView not at the server. This will help us to improve the UX and speed of the Application

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by rahullli** [comment]
I want to work on this issue

**Comment by Pranshu-Tripathi** [comment]
I would like to work on this issue.
@rahullli are you working on still this??

**Comment by Ashutoshgupta22** [comment]
can I look into this ?

**Comment by riturajjain2000** [comment]
I am working on it :)

**Comment by adiig7** [comment]
@riturajjain2000 are you still working on it?

**Comment by riturajjain2000** [comment]
> @riturajjain2000 are you still working on it?

No, as I'm not able to understand the issue fully , you can work on it

**Comment by Medhavi-16** [comment]
I am interested in working on this issue?

**Comment by Goheljay** [comment]
i want to work on this issue. I am interested.

**Comment by yash0208** [comment]
I Want To Work On The Issue I Might Like Working On This Kind Of Issues.

**Comment by Shhreyya** [comment]
**I want to resolve this issue.**

**Comment by mannandeep** [comment]
Can I work on this issue, or is being worked on by someone right now?

**Comment by Prashant830** [comment]
I've solved it, can I hit a PR?

**Comment by nileshteji** [comment]
I think no other PR'S have been attached to this issue .You could go ahead
