### ISSUE TITLE
On Screen configuration  edit data change

### ISSUE THREAD

**Issue by Prince-kushwaha** [fossasia/open-event-organizer-android#2121]
**Describe the bug**
In edit profile when i edit profile data or change data . on  screen configurations change edit data 
erased  
and in landscrope mode layout not fit

**Screenshots**
![20200620_192939](https://user-images.githubusercontent.com/65972015/85203682-f515c900-b32c-11ea-8447-c3b2538f565c.gif)

**Smartphone Info:**

|Device         ||
|Android Version|    |

**Would you like to work on the issue?**

  Yes

**Comment by Prince-kushwaha** [comment]
i am working on this issue

**Comment by Prince-kushwaha** [comment]
I am working on this issue

**Comment by rasacharjee** [comment]
@Prince-kushwaha are you still working on the issue? If not, can I work on the issue.

**Comment by nulllpointerexception** [comment]
i am working on this

**Comment by adiig7** [comment]
@nulllpointerexception are you still wotking?

**Comment by nulllpointerexception** [comment]
yes

**Comment by Prince-kushwaha** [comment]
is this bug is fixed?
