### ISSUE TITLE
bug:phone(edit text) hide behind  Done button in landscape orientation

### ISSUE THREAD

**Issue by Prince-kushwaha** [fossasia/open-event-organizer-android#2122]
**Describe the bug**
phone  edittext hide behind the "Done" button.
Scrolling won't help here to reach to phone edittext.

**To Reproduce**

![Screenshot_2020-06-25-09-56-06-783_com eventyay organizer](https://user-images.githubusercontent.com/65972015/85653835-2f83bb00-b6cb-11ea-8ddc-bbc2851246f8.jpg)

**Smartphone Info:**

|Device         |  Redmi y3|
|Android Version|   9.0 (Pie) |

**Would you like to work on the issue?**
 Yes

**Comment by Prince-kushwaha** [comment]
I am working on this issue

**Comment by nileshteji** [comment]
@Prince-kushwaha  Is this issue Completed?

**Comment by ritmojs** [comment]
I want to work on this issue.

**Comment by liveHarshit** [comment]
@ritmojs Please go ahead

**Comment by liveHarshit** [comment]
fixed
