### ISSUE TITLE
Add a dialog notifying that the app is prototype

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-organizer-android#2176]
Add popup screen: "This mobile app is still in its prototype stage with many features being experimental. We currently recommend using this app only for testing."

The popup should only display once

**Comment by nileshteji** [comment]
@iamareebjamal  working on this issue

**Comment by mishra5047** [comment]
Hi @iamareebjamal should i work on this issue?

**Comment by sandhukaran28** [comment]
Hey Sir, I would like to work on this issue

**Comment by mohitbahadure** [comment]
I would like to work on this issue

**Comment by iamareebjamal** [comment]
Please don't just comment I want to work on this issue. Send a PR after commenting. 4 people have commented in a week and not a single PR

**Comment by nileshteji** [comment]
@iamareebjamal The Project is not able to build .I have raised the concern multiple types on Gitter Chanel.

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/open-event-organizer-android/runs/1323277639
https://circleci.com/gh/fossasia/open-event-organizer-android/4071?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

It is able to build in both these places. You have to either update the project to latest gradle or downgrade your tooling to older version which is used in the project. First is easier to do
