### ISSUE TITLE
Timeout error in the login activity

### ISSUE THREAD

**Issue by varunvjha** [fossasia/open-event-organizer-android#2207]
**Describe the bug**
As soon as the email address is entered and Get Started is clicked, it almost always shows "timeout" at the bottom of the screen.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Nexus 6|
|Android Version |Android 10|

**Would you like to work on the issue?**

- [ ] Yes
- [x] No

**Comment by mdzaidalam52** [comment]
I want to work on this. Please do assign me this issue.

**Comment by iamvs-2002** [comment]
@varunvjha Are you talking about Connection timeout?
