### ISSUE TITLE
I think the email verification is not working

### ISSUE THREAD

**Issue by raghavpartani** [fossasia/open-event-organizer-android#2232]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**Smartphone Info:**

|               | |
|---------------|-|
|Device         ||
|Android Version|    |

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [x] No
- Other:

**Comment by prince02765** [comment]
Yes, I would Like to work on this issue.
