### ISSUE TITLE
In update profile section there is no validation on phone number

### ISSUE THREAD

**Issue by raghavpartani** [fossasia/open-event-organizer-android#2233]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**Smartphone Info:**

|               | |
|---------------|-|
|Device         ||
|Android Version|    |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by toth2000** [comment]
Can I work this issue?
