### ISSUE TITLE
Add create attendee feature

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-organizer-android#519]
"Create attendee" option should be given in the app which can be used for payment on site case.

@iamareebjamal what do you say?

**Comment by iamareebjamal** [comment]
Sure, but the flow is a little bit complex now. Check [this](https://github.com/fossasia/open-event-orga-server/issues/4328)

**Comment by Masquerade0097** [comment]
@iamareebjamal I would like to work on this. Please provide the necessary details.

**Comment by iamareebjamal** [comment]
This is still somewhat out of scope for the app now.
