### ISSUE TITLE
Enter recovery token and request new password

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-organizer-android#578]
Parent Issue #548 

**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    

**Feature Description**

User will enter the recovery token received on his email along with a new password to reset his password. Server will then patch the previous password associated with that email.
 
**Would you like to work on the issue?**
Yes

**Comment by hpdang** [comment]
The current password reset process is not usable for mobile users. It is easy if you are on your laptop but not on phone. Please see below: 

* I requested password reset from my phone: 
![WhatsApp Image 2019-07-07 at 09 42 55](https://user-images.githubusercontent.com/1658742/60765583-1db19e00-a09d-11e9-94a3-c137cec9e11a.jpeg)

* This is what I got in my mailbox: 
![Screenshot from 2019-07-07 09-51-33](https://user-images.githubusercontent.com/1658742/60765578-04a8ed00-a09d-11e9-8f5d-dc21a9b3a1b3.png)

* User's behavior & action: 
- Users are confused TOKEN vs. RESET LINK 
- Users must copy the end part of the link after the word 'token='
- It is not easy to copy that specific string of numbers with the phone 

* Proposal: 
What could be the simplest way to fix this? 
I thought of something like this: 
Option 1: Replace the old message with a new message including only the Token
- 'Please copy and paste this token into your app [TOKEN]' 

Option 2: Keep the current message and include an additional instruction for phone users 
- 'Please copy and paste this token into your app [TOKEN]'

**Comment by ShridharGoel** [comment]
@hpdang The process is now better: #1797

**Comment by ShridharGoel** [comment]
Password reset email updated: https://github.com/fossasia/open-event-server/pull/6164
