### ISSUE TITLE
Event List not updating automatically after creation

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-organizer-android#690]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

After an event is created, the list is not updated automatically

**Expected Behaviour**

- [ ] Once the event is created, it's response is the event itself and hence should be saved in the repository on receiving.
- [ ] Then, a change listener should be created in the event list presenter, so that any change in database is reflected in the list

**Comment by Masquerade0097** [comment]
@iamareebjamal Can i work on it?

**Comment by iamareebjamal** [comment]
Sure, please go ahead

**Comment by mishuvs** [comment]
@Masquerade0097 Are you working on this?

**Comment by Masquerade0097** [comment]
Sorry, I'll work on it.

**Comment by sridharjajoo** [comment]
@Masquerade0097 Are you working on it?

**Comment by Masquerade0097** [comment]
@sridharjajoo  No.

**Comment by sridharjajoo** [comment]
So I am taking up this issue :)

**Comment by sridharjajoo** [comment]
@iamareebjamal I have implemeted the change listener so that any change in database can be reflected in the list but still the events are not getting shown up.The created event is already getting saved in the repository right?

**Comment by iamareebjamal** [comment]
Yes

**Comment by srv-twry** [comment]
@sridharjajoo Are you stil working on this ? If no, then i will take it. If yes and still facing the problem, then IMO you should open a WIP PR so that others can point out the mistake if any.

**Comment by sridharjajoo** [comment]
@srv-twry I was actually on this issue but for the past few days the event creation wasn't taking place and hence I was not able to go any further. But since the latest commit event creation is taking place and I will be again working on it. If I encounter any problem I'll surely ask.

**Comment by iamareebjamal** [comment]
Nevertheless create a WIP PR. The reason list is not updated is because once createventactivity is opened, the database listener(even when it is added), stops listening and one the event is created and the activity is closed, the database loading takes place and for some reason returns the old event list and not the new one

**Comment by sridharjajoo** [comment]
@iamareebjamal If it's not an issue can I make a WIP PR by day after tomorrow? Actually I don't have my laptop currently.

**Comment by sridharjajoo** [comment]
@iamareebjamal Should I create a bottomsheetfragment for the creation of new event rather than opening a new activity? I think then the event list will get updated automatically.

**Comment by iamareebjamal** [comment]
No, the form is too big for BottomSheetView, you can use standard fragment though
