### ISSUE TITLE
Compare Petix ticketing app and check possibilities to use it with Open Event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-organizer-android#79]
Petixdroid is a new ticketing app. Please check if we can use it and implement features we need: https://github.com/pretix/pretixdroid

**Comment by mejariamol** [comment]
Petrixdroid has implemented **ticket validation** and **ticket/attendee search** requests in the api itself. We can do the same which will improve performance of the app in large data set cases.

**Comment by mariobehling** [comment]
Ok, but on the list of upcoming features Petixdroid says they will support offline functionalities as well. Are there mixed options? How does Eventbrite do it in the organizer app? It is performing well.

**Comment by mejariamol** [comment]
To support offline functionalities, the preferred way will be 

1. maintaining required local database on the client side

2. then data sync using Websocket implementation 

Like how Gmail app does.. User can delete messages or save drafts even in the offline mode, and when the app comes online, the changes are synced with server side database..

But then **_check in/out functionality_** can't be supported on more than one device at a time.

**Comment by niranjan94** [comment]
> But then check in/out functionality can't be supported on more than one device at a time.

Why not ?

**Comment by mejariamol** [comment]
If app is working offline, just updating local database.. Then there may arise cases of multi checked-ins on same ticket code at different host apps.

**Comment by niranjan94** [comment]
> If app is working offline, just updating local database.. Then there may arise cases of multi checked-ins on same ticket code at different host apps.

The app isn't always gonna work offline. Internet connection would be preferred. Only on emergency cases or if there is no internet, would it be working offline. So, in those times, a few cases of multi-check-ins are acceptable.

**Comment by mejariamol** [comment]
Okay... Then what will be preferred implementation ??  Websocket??

**Comment by niranjan94** [comment]
@mejariamol we cannot decide on that just yet. Because it would require changes in the server too and that is a not a decision we can make just with a single feature in mind. For now, let's stick to the APIs we have. We'll come to a decision by the end of the bonding period. (we'd have an idea of the selected students/projects and we can plan with all that in mind)
