### ISSUE TITLE
Bug: StrictMode VmPolicy voilation with POLICY_DEATH 

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-organizer-android#836]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

On app startup, rotating the screen leads to a crash

**Expected Behaviour**

It shouldn't crash.

**Steps to reproduce it**

1. Open the app
2. Rotate the screen
3. The app crashes. 
If it doesn't crash try rotating a couple of times more. 

**LogCat for the issue**

```
03-25 11:58:28.015 26927-26927/org.fossasia.eventyay W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
03-25 11:58:28.015 26927-26927/org.fossasia.eventyay I/Process: Sending signal. PID: 26927 SIG: 9
03-25 11:58:28.015 26927-26927/org.fossasia.eventyay V/Process: killProcess [26927] Callers=android.os.StrictMode.onVmPolicyViolation:1688 android.os.StrictMode.decrementExpectedActivityCount:2059 android.app.ActivityThread.performDestroyActivity:3921 android.app.ActivityThread.handleDestroyActivity:3932
```

**Screenshots of the issue**

![videotogif_2018 03 25_12 01 41](https://user-images.githubusercontent.com/21277837/37872425-4955172e-3025-11e8-843c-f09682501ca5.gif)

**Android version and Phone Model**

Oppo f1 Android 5.1.1
    
**Would you like to work on the issue?**

No, since i am unable to make anything of the error. 
@iamareebjamal Can you take a look at this please ?

**Comment by iamareebjamal** [comment]
Change `penaltyDeath` to `penaltyLog` in OrgaApplication to get the log of error

I'm trying to fix this as well. This is related to memory leaks

**Comment by iamareebjamal** [comment]
I think it is related to dependency upgrades. Can you checkout a previous version and confirm?

**Comment by srv-twry** [comment]
Yes, i think so. I checked out ```HEAD~6``` and it works fine.

**Comment by iamareebjamal** [comment]
No, it's due to #834, I removed detaching presenters by mistake. Fixing

**Comment by srv-twry** [comment]
It is still happening. 
@sridharjajoo @mishuvs Can you verify if the app still crashes making sure that you use the `development` branch.

**Comment by mishuvs** [comment]
Yes, the app crashes with the same error on `development` branch, but is not consistently reproducible. In my case sometimes it crashes when rotated multiple times continually, and sometimes in just one cycle rotation.

**Comment by iamareebjamal** [comment]
For now, remove penalty death and add penalty log and dialog.

This is mainly due to false positive memory leak @sridharjajoo @Masquerade0097 @srv-twry @mishuvs

**Comment by iamareebjamal** [comment]
Reopening because cause is not fixed
